# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['submited']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='article_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=datetime.datetime(2018, 7, 14, 17, 35, 26, 935348, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
