# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainshare', '0002_auto_20180714_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(default=datetime.datetime(2018, 7, 14, 17, 54, 51, 896403, tzinfo=utc), upload_to='categories/'),
            preserve_default=False,
        ),
    ]
