# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshare', '0004_auto_20180719_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
